USE geolocalizacao;
DROP TABLE IF EXISTS patente;
CREATE TABLE patente (
  id smallint(4) NOT NULL AUTO_INCREMENT,
  nome varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

LOCK TABLES patente WRITE;
INSERT INTO patente VALUES (1,'SOLDADO');
UNLOCK TABLES;